class Collections:
    USERS = 'users'
    PASSWORD = 'password'
    TEMP_PASSPORT = 'temp_passport'
    ACCESS_TOKENS = 'access_tokens'
    RATE_LIMITS = 'rate_limits'
    REQUEST_TRACKER = 'request_tracker'
    NOTIFICATIONS = 'notifications'
    DEVICE_TOKENS = 'device_tokens'
    MULTIPART_UPLOAD = 'multipart_upload'
    MULTIPART_ETAGS = 'multipart_etags'
    OTP = 'otp'
    ITEMS = 'items'
    LISTINGS = 'listings'
    UNIVERSITIES = 'universities'
    TRANSACTIONS = 'transactions'
