EXCEPTION_ADMIN_NOT_FOUND = 'Admin does not exist'
EXCEPTION_DEVICE_TOKEN_INVALID = 'Invalid device token'
EXCEPTION_EMAIL_EXISTS = 'Email already exists'
EXCEPTION_EMAIL_NOT_REGISTERED = 'There is no email not registered for this user'
EXCEPTION_PHONE_EXISTS = 'Phone already exists'
EXCEPTION_UNIVERSITY_ID_EXISTS = 'University Id already exists'
EXCEPTION_USERNAME_PASSWORD_INVALID = 'Incorrect username or password'
EXCEPTION_EMAIL_PASSWORD_INVALID = 'Incorrect email or password'
EXCEPTION_FORBIDDEN_ACCESS = 'Access denied'

EXCEPTION_OTP_ALREADY_SENT = 'OTP already sent. Please try again after 5 mins'
EXCEPTION_OTP_EXPIRED = 'OTP expired'
EXCEPTION_OTP_INVALID = 'Invalid OTP'
EXCEPTION_OTP_NOT_FOUND = 'OTP not found'

EXCEPTION_PASSWORD_CREATE = 'Please create password'
EXCEPTION_PASSWORD_EXISTS = 'Password already exists'
EXCEPTION_PASSWORD_INVALID = 'Invalid password'
EXCEPTION_PASSWORD_MISMATCH = 'Password mismatch'
EXCEPTION_PASSWORD_NOT_FOUND = 'Password not created'

EXCEPTION_UNAUTHORIZED_ACCESS = 'Unauthorised access'

EXCEPTION_USER_NOT_FOUND = 'User not found'
EXCEPTION_USER_NOT_VERIFIED = 'User not verified'

EXCEPTION_TOKEN_INVALID = 'Invalid access token'
EXCEPTION_TOKEN_EXPIRED = 'Access token expired'
EXCEPTION_REFRESH_TOKEN_INVALID = 'Invalid refresh token'
EXCEPTION_AUTHORIZATION_HEADER_INVALID = 'Authorization header invalid'
EXCEPTION_AUTHORIZATION_TOKEN_NOT_FOUND = 'Authorization token not found'
EXCEPTION_ACCOUNT_INACTIVE = 'Account is inactive'
EXCEPTION_REFRESH_TOKEN_INVALID = 'Invalid refresh token'
EXCEPTION_API_CONNECTION_FAILURE = 'Error connecting to the API'
EXCEPTION_JSON_DECODER_ERROR = 'Json encoder error'
EXCEPTION_UNKNOWN_ERROR = 'Unknown error'
EXCEPTION_S3_UPLOAD_FAILED = 'S3 upload failed'
EXCEPTION_MULTIPART_NOT_FOUND = 'Multipart not found'
EXCEPTION_PERMISSION_DENIED = 'Permission denied'
EXCEPTION_ITEM_NOT_FOUND = 'Item not found'
EXCEPTION_LISTING_NOT_FOUND = 'Listing not found'
EXCEPTION_LISTING_MARKED_SOLD = 'Listing marked as sold cannot be updated'
EXCEPTION_EXISTING_ITEM = 'Item already exists'
EXCEPTION_INTEREST_DUPLICATE = 'User already added to the interested list'
EXCEPTION_ITEM_SOLD = 'Item already sold'
EXCEPTION_INTEREST_NOT_FOUND = 'Interest not found'
EXCEPTION_UNAUTHORIZED_SALE = 'User is not authorized to mark sale as complete'
EXCEPTION_UNAUTHORIZED_INTEREST = 'Seller not allowed to mark interest'
